remote_theme: carlosperate/jekyll-theme-rtd
site_author: sunset-hue
repo_url: "https://github.com/sunset-hue/inkcord"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist